
DROP DATABASE IF EXISTS GroceryList;

CREATE DATABASE IF NOT EXISTS GroceryList;

USE GroceryList;

CREATE TABLE IF NOT EXISTS Items(
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    INDEX(name)
) ENGINE INNODB;

INSERT INTO Items(name)
VALUES
	("Milk 2% - Publix");

CREATE TABLE IF NOT EXISTS GroceryLists(
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    list_date DATETIME NOT NULL DEFAULT(NOW())
) ENGINE INNODB;

CREATE TABLE IF NOT EXISTS GroceryListItems(
    list_id INT UNSIGNED NOT NULL,
    item_id INT UNSIGNED NOT NULL,
    quantity INT UNSIGNED NOT NULL DEFAULT 1,
    FOREIGN KEY(list_id) REFERENCES GroceryLists(id),
    FOREIGN KEY(list_id) REFERENCES Items(id)
) ENGINE INNODB;
    
SELECT LAST_INSERT_ID();
